name: Convert Jupyter Notebooks to HTML

on:
  push:
    branches:
      - main
    paths:
      - '**.ipynb'

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert
    - name: Convert Notebooks to HTML
      run: |
        mkdir -p html
        for notebook in $(find . -name "*.ipynb"); do
          jupyter nbconvert --to html $notebook --output-dir html
        done
    - name: Commit and push if changed
      run: |
        git config --global user.email "380715946@qq.com"
        git config --global user.name "GDSmonster"
        git add html/*
        git commit -m "Updated HTML files"
        git push
